a=(12,45,33,88,34,"Ahamed")
b=(12,45,3,3,88,34,12,3,546,6,67,5,3,30)
print("Type:",type(a))
print("Length:",len(a))
print("Elements in a using for loop:")
for i in a:
    print(i)

print("\n\nSlicing:")
print("1.Forward slicing")
print(a[1:3])
print(a[:3])
print(a[1:])
print("1.Backward slicing")
print(a[-1:-3])
print(a[:-3])
print(a[-1:])
print('\n\nMIN MAX and COUNT')
print("Minimum:",min(b))
print("Maximum",max(b))
print("The number of times 3 is repeated is:",b.count(3))
