a={1,23,43,5,3,654,43,54,23,5,5,5,654,78,78,9}
print("Type:",type(a))
print("Given values to set are:a={1,23,43,5,3,654,43,54,23,5,5,5,654,78,78,9}")
print("Printing a:",a)

print("Length:",len(a))
print("Minimum:",min(a))
print("Maximum:",max(a))
print("Adding Ahamed")
a.add('Ahamed')
print(a)
print("Adding Kabeer")
a.add('Kabeer')
print(a)
print("Updating Python")
a.update("Python")
print(a)
print("Updating [Python]")
a.update(["Python"])
print(a)
print("Updating [Python,Course]")
a.update(["Python","Course"])
print(a)

print("Pop:")
a.pop()
print(a)
print("Pop:")
a.pop()
print(a)
print("Pop:")
a.pop()
print(a)
print("Remove Ahamed:")
a.remove('Ahamed')
print(a)
print("Discard Kabeer:")
a.discard('Kabeer')
print(a)
print("Clear:")
a.clear()
print(a)




